# Generated by Django 4.1.7 on 2023-03-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.CharField(max_length=100)),
                ('release_date', models.CharField(max_length=100)),
                ('lte_exists', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, null=True)),
            ],
        ),
    ]
